### ISSUE TITLE
devKit>Readme

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-sojourn#42]
**Tasks**
- [x] Getting Started Text
- [x] Install Text
- [x] Short Description of project text
- [x] Short Description of [Imagineering] text
- [x] Call to Action (CTA) to devKit location

**Design**
![readme2](https://user-images.githubusercontent.com/5770007/48141563-29806280-e279-11e8-928f-0829e61cdb90.png)
